# Generated by Django 5.2.4 on 2025-07-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default=''),
        ),
    ]
