# Generated by Django 5.2.4 on 2025-07-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_useraddress_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='name',
            new_name='address',
        ),
    ]
